<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Silicon Output</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>output.error</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(\d+:\d+:\s+.*)</string>
			<key>name</key>
			<string>meta.output.error</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>output.success</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(No errors found\.)</string>
			<key>name</key>
			<string>meta.output.success</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.silicon</string>
	<key>uuid</key>
	<string>8e495189-457a-4dc0-bf3d-7c22d8045834</string>
</dict>
</plist>
