<!--
  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.
  
  Copyright (c) 2011-2021 ETH Zurich.
  -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>scopeName</key>
    <string>source.silver</string>
    <key>fileTypes</key>
    <array>
      <string>viper</string>
    </array>
    <key>name</key>
    <string>Viper</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#declarations</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.silver</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.silver</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.silver</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(//::).*$\n?</string>
            <key>name</key>
            <string>comment.line.error-annotation.silver</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.silver</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.silver</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(false|true|null|write|none|wildcard)\b</string>
            <key>name</key>
            <string>constant.language.silver</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;![\w$])((\+|-)?[0-9]+)\b</string>
            <key>name</key>
            <string>constant.numeric.silver</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(Bool|Int|Ref|Perm|Rational|Set|Seq|Multiset|Map)\b</string>
            <key>name</key>
            <string>storage.type.primitive.silver</string>
          </dict>
        </array>
      </dict>
      <key>declarations</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.silver</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.silver</string>
              </dict>
            </dict>

            <key>match</key>
            <string>\b(unique\s+)?(function)\b(\s+([$\w]+(\.\[$\w])?))?</string>
            <key>name</key>
            <string>meta.function.silver</string>
            <key>patterns</key>
            <dict>
              <key>include</key>
              <string>#parameter-list</string>
            </dict>

            
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.silver</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.silver</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(axiom)\b(\s+([$\w]+(\.[$\w]+)?))?</string>
            <key>name</key>
            <string>meta.axiom.silver</string>
            <key>patterns</key>
            <dict>
              <key>include</key>
              <string>#parameter-list</string>
            </dict>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.silver</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.silver</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(import)\b(\s+(".*?"|<.*?>))?</string>
            <key>name</key>
            <string>meta.import.silver</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.silver</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.silver</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(predicate)\b(\s+([$\w]+(\.[$\w]+)?))?</string>
            <key>name</key>
            <string>meta.predicate.silver</string>
            <key>patterns</key>
            <dict>
              <key>include</key>
              <string>#parameter-list</string>
            </dict>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.silver</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.silver</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(method)\b(\s+([$\w]+(\.[$\w]+)?))?</string>
            <key>name</key>
            <string>meta.method.silver</string>
            <key>patterns</key>
            <dict>
              <key>include</key>
              <string>#parameter-list</string>
            </dict>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.silver</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.silver</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(domain)\b</string>
            <key>name</key>
            <string>meta.domain.silver</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.declaration.silver</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.silver</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\b(adt)\b</string>
            <key>name</key>
            <string>meta.adt.silver</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>::</string>
            <key>name</key>
            <string>punctuation.separator.forall.silver</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b((assume|inhale)\s+false)\b</string>
            <key>name</key>
            <string>keyword.warning.silver</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(var|returns|field)\b</string>
            <key>name</key>
            <string>keyword.declaration.variables.silver</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(define)\b</string>
            <key>name</key>
            <string>keyword.declaration.namedassertions.silver</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(if|else|elseif|while|statelabel|label|goto)\b</string>
            <key>name</key>
            <string>keyword.control.flow.silver</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(acc|forperm|forall|exists|folding|unfolding|packaging|applying|old|perm|result|let)\b</string>
            <key>name</key>
            <string>keyword.other.verification.expression.silver</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(domain|range)\b\s*\(</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.verification.expression.silver</string>              
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(assert|inhale|exhale|assume|fold|unfold|package|apply|wand|fresh|constraining)\b</string>
            <key>name</key>
            <string>keyword.other.verification.statement.silver</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(requires|ensures|invariant|decreases)\b</string>
            <key>name</key>
            <string>keyword.other.verification.contracts.silver</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(new)\b</string>
            <key>name</key>
            <string>keyword.other.other.silver</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(union|in|intersection|setminus|\+\+|subset)\b</string>
            <key>name</key>
            <string>keyword.other.operations.silver</string>
          </dict>
        </array>
      </dict>
      <key>parameter-list</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.silver</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.silver</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter.silver</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.class.silver</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>([_$a-zA-Z][_$\w]*)\s*:\s*([_$a-zA-Z][_$\w]*)?</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.separator.parameters.silver</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>trigger-list</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.trigger.begin.silver</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.trigger.end.silver</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>.*?</string>
                <key>name</key>
                <string>entity.name.trigger.silver</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>uuid</key>
      <string>510359d3-78b1-4310-b440-63c3b5ab821c</string>
    </dict>
  </dict>
</plist>