<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sil</string>
	</array>
	<key>name</key>
	<string>Silver</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#declarations</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.silver</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.silver</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.silver</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//::).*$\n?</string>
					<key>name</key>
					<string>comment.line.error-annotation.silver</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.silver</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.silver</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(false|true|null|write|none|wildcard|result)\b</string>
					<key>name</key>
					<string>constant.language.silver</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((\+|-)?[0-9]+)\b</string>
					<key>name</key>
					<string>constant.numeric.silver</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Bool|Int|Ref|Perm)\b</string>
					<key>name</key>
					<string>storage.type.primitive.silver</string>
				</dict>
			</array>
		</dict>
		<key>declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.silver</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.silver</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(function)\b\s+(\w+(\.\w+)?)</string>
					<key>name</key>
					<string>meta.function.silver</string>
					<key>patterns</key>
					<dict>
						<key>include</key>
						<string>#parameter-list</string>
					</dict>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.silver</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.silver</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(predicate)\b\s+(\w+(\.\w+)?)</string>
					<key>name</key>
					<string>meta.predicate.silver</string>
					<key>patterns</key>
					<dict>
						<key>include</key>
						<string>#parameter-list</string>
					</dict>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.silver</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.silver</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(method)\b\s+(\w+(\.\w+)?)</string>
					<key>name</key>
					<string>meta.method.silver</string>
					<key>patterns</key>
					<dict>
						<key>include</key>
						<string>#parameter-list</string>
					</dict>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(field)\b</string>
					<key>name</key>
					<string>keyword.declaration.fields.silver</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(var)\b</string>
					<key>name</key>
					<string>keyword.declaration.variables.silver</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(define)\b</string>
					<key>name</key>
					<string>keyword.declaration.namedassertions.silver</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(if|else|while)\b</string>
					<key>name</key>
					<string>keyword.control.flow.silver</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(requires|ensures|invariant)\b</string>
					<key>name</key>
					<string>keyword.other.contracts.silver</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(acc|fresh|constraining)\b</string>
					<key>name</key>
					<string>keyword.other.permissions.silver</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(in|inhale|exhale|assert|assume|fold|unfold|folding|unfolding|package|apply|packaging|applying|wand|forall|exists|forallrefs|old)\b</string>
					<key>name</key>
					<string>keyword.other.verification.silver</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(new|let|returns|statelabel)\b</string>
					<key>name</key>
					<string>keyword.other.other.silver</string>
				</dict>
			</array>
		</dict>
		<key>parameter-list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.silver</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.silver</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.silver</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.class.silver</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([_$a-zA-Z][_$\w]*)\s*:\s*([_$a-zA-Z][_$\w]*)?</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.parameters.silver</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.silver</string>
	<key>uuid</key>
	<string>510359d3-78b1-4310-b440-63c3b5ab821c</string>
</dict>
</plist>
